version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  java-app:
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener:latest
    ports:
      - "9000:9000"
      - "9443:9443"  # Expose both HTTP and HTTPS ports
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./src:/app/src  # Mount source code in a different directory
      - ~/.m2:/root/.m2  # Keep Maven repository mount

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - java-app  # Ensure that kafka starts after java-app

networks:
  backend:
