version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  java-app:
    image: urlshortener:latest
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
