version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  java-app:
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener:latest
    ports:
      - "9000:9000"
      - "9443:9443"  # Expose both HTTP and HTTPS ports
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./src:/app/src  # Mount source code in a different directory
      - ~/.m2:/root/.m2  # Keep Maven repository mount

networks:
  backend:
