apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pawan.yadav\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: java-app
  name: java-app
spec:
  type: NodePort  # Change this to NodePort
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: 30001
  selector:
    io.kompose.service: java-app
status:
  loadBalancer: {}
