apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\pawan.yadav\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: java-app
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: java-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\pawan.yadav\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f .\docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/urlshortener-backend: "true"
        io.kompose.service: java-app
    spec:
      containers:
        - image: urlshortener:latest
          imagePullPolicy: IfNotPresent
          name: java-app
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
