CREATE TABLE url_mapping
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_url  VARCHAR(512),
    shortened_url VARCHAR(20),
    CONSTRAINT pk_url_mapping PRIMARY KEY (id)
);
