apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          imagePullPolicy: IfNotPresent  
          image: urlshortener:latest
          ports:
            - containerPort: 9000
          # Add environment variables if required
